apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc-prod-validadorcpf
spec:
  type: NodePort
  selector: 
    app: label-pod-rodrigo-prod-validadorcpf
  ports:
    - port: 8081
      nodePort: 30012